/**
 * Gateway authentication for the web server (LAN mode security layer).
 *
 * - The access key is persisted as a scrypt hash + salt in
 *   `<home>/web-gateway.json` (0600). The plaintext key is never written to
 *   disk; it lives in memory only for the run that created or supplied it.
 * - Browser sessions are cookie-based (HttpOnly, SameSite=Lax, 30 days) so
 *   the key never lands in URLs or browser history.
 * - Loopback requests are always trusted, so the local `--open` flow works
 *   without entering a key.
 * - All key comparisons use timing-safe primitives.
 */

import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { chmod, readFile, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const GATEWAY_FILE = 'web-gateway.json';
export const GATEWAY_COOKIE_NAME = 'scream_gateway';
const SESSION_TTL_SECONDS = 30 * 24 * 60 * 60; // 30 days
const SCRYPT_KEYLEN = 64;
const SALT_LEN = 16;

interface StoredGatewayKey {
  readonly version: 1;
  readonly salt: string; // hex
  readonly hash: string; // hex
  readonly createdAt: string; // ISO timestamp
}

/** In-process gateway state: key verification material + live sessions. */
export class GatewayAuth {
  /** Plaintext key, present only when it entered memory this run. */
  readonly plaintext: string | null;
  /** True when the key was freshly generated by this run. */
  readonly generated: boolean;

  private readonly filePath: string;
  private readonly salt: Buffer;
  private readonly hash: Buffer;
  private readonly sessions = new Map<string, number>(); // sid → expiresAt (ms)

  private constructor(input: {
    filePath: string;
    salt: Buffer;
    hash: Buffer;
    plaintext: string | null;
    generated: boolean;
  }) {
    this.filePath = input.filePath;
    this.salt = input.salt;
    this.hash = input.hash;
    this.plaintext = input.plaintext;
    this.generated = input.generated;
  }

  /**
   * Resolves the gateway key for an enabled gateway:
   * 1. explicit `--token` (persisted, replacing any stored key),
   * 2. previously stored key file,
   * 3. freshly generated key (persisted).
   */
  static async setup(opts: { homeDir: string; token?: string }): Promise<GatewayAuth> {
    const filePath = join(opts.homeDir, GATEWAY_FILE);
    if (opts.token !== undefined && opts.token.length > 0) {
      const salt = randomSalt();
      const record: StoredGatewayKey = {
        version: 1,
        salt: salt.toString('hex'),
        hash: scryptSync(opts.token, salt, SCRYPT_KEYLEN).toString('hex'),
        createdAt: new Date().toISOString(),
      };
      await persistKey(filePath, record);
      return new GatewayAuth({
        filePath,
        salt,
        hash: Buffer.from(record.hash, 'hex'),
        plaintext: opts.token,
        generated: false,
      });
    }

    const stored = await loadStoredKey(filePath);
    if (stored) {
      return new GatewayAuth({
        filePath,
        salt: Buffer.from(stored.salt, 'hex'),
        hash: Buffer.from(stored.hash, 'hex'),
        plaintext: null,
        generated: false,
      });
    }

    const plaintext = randomBytes(12).toString('base64url');
    const salt = randomSalt();
    const record: StoredGatewayKey = {
      version: 1,
      salt: salt.toString('hex'),
      hash: scryptSync(plaintext, salt, SCRYPT_KEYLEN).toString('hex'),
      createdAt: new Date().toISOString(),
    };
    await persistKey(filePath, record);
    return new GatewayAuth({
      filePath,
      salt,
      hash: Buffer.from(record.hash, 'hex'),
      plaintext,
      generated: true,
    });
  }

  /** Timing-safe key verification against the stored scrypt hash. */
  verifyKey(key: string): boolean {
    if (key.length === 0) return false;
    const candidate = scryptSync(key, this.salt, SCRYPT_KEYLEN);
    return timingSafeEqual(candidate, this.hash);
  }

  createSession(): string {
    this.pruneExpired();
    const sid = randomBytes(32).toString('base64url');
    this.sessions.set(sid, Date.now() + SESSION_TTL_SECONDS * 1000);
    return sid;
  }

  verifySession(cookieHeader: string | undefined): boolean {
    const sid = parseCookies(cookieHeader)[GATEWAY_COOKIE_NAME];
    if (sid === undefined) return false;
    const expiresAt = this.sessions.get(sid);
    if (expiresAt === undefined) return false;
    if (Date.now() >= expiresAt) {
      this.sessions.delete(sid);
      return false;
    }
    return true;
  }

  destroySession(cookieHeader: string | undefined): void {
    const sid = parseCookies(cookieHeader)[GATEWAY_COOKIE_NAME];
    if (sid !== undefined) this.sessions.delete(sid);
  }

  sessionCookie(sid: string): string {
    return `${GATEWAY_COOKIE_NAME}=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${SESSION_TTL_SECONDS}`;
  }

  clearCookie(): string {
    return `${GATEWAY_COOKIE_NAME}=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0`;
  }

  private pruneExpired(): void {
    const now = Date.now();
    for (const [sid, expiresAt] of this.sessions) {
      if (now >= expiresAt) this.sessions.delete(sid);
    }
  }
}

/** Loopback requests are trusted without a key (local `--open` flow). */
export function isLoopbackAddress(address: string | undefined): boolean {
  return address === '127.0.0.1' || address === '::1' || address === '::ffff:127.0.0.1';
}

export function parseCookies(header: string | undefined): Record<string, string> {
  const out: Record<string, string> = {};
  if (!header) return out;
  for (const part of header.split(';')) {
    const eq = part.indexOf('=');
    if (eq <= 0) continue;
    const name = part.slice(0, eq).trim();
    const raw = part.slice(eq + 1).trim();
    if (name.length === 0) continue;
    try {
      out[name] = decodeURIComponent(raw);
    } catch {
      out[name] = raw;
    }
  }
  return out;
}

/** Gate outcome for a request reaching a LAN-enabled gateway. */
export type GatewayVerdict = 'allow' | 'redirect' | 'unauthorized';

/**
 * Pure decision for the HTTP gateway gate, factored out of server.ts so it
 * can be unit-tested without real sockets.
 */
export function gatewayVerdict(input: {
  loopback: boolean;
  authenticated: boolean;
  path: string;
  method: string;
  apiPrefix: string;
}): GatewayVerdict {
  if (input.loopback || input.authenticated) return 'allow';
  if (input.path === '/gateway') return 'allow';
  if (input.path === `${input.apiPrefix}/gateway/status`) return 'allow';
  if (input.path === `${input.apiPrefix}/gateway/login`) return 'allow';
  if (input.path === `${input.apiPrefix}/gateway/logout`) return 'allow';
  if (input.path.startsWith(`${input.apiPrefix}/`)) return 'unauthorized';
  if (input.method === 'GET') return 'redirect';
  return 'unauthorized';
}

function randomSalt(): Buffer {
  return randomBytes(SALT_LEN);
}

async function loadStoredKey(filePath: string): Promise<StoredGatewayKey | null> {
  let raw: string;
  try {
    raw = await readFile(filePath, 'utf-8');
  } catch {
    return null;
  }
  try {
    const parsed = JSON.parse(raw) as StoredGatewayKey;
    if (
      parsed?.version !== 1 ||
      typeof parsed.salt !== 'string' ||
      typeof parsed.hash !== 'string' ||
      parsed.salt.length === 0 ||
      parsed.hash.length === 0
    ) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

/** Atomic persist: temp file (0600) + rename, then verify the mode. */
async function persistKey(filePath: string, record: StoredGatewayKey): Promise<void> {
  const tmp = `${filePath}.tmp`;
  await writeFile(tmp, `${JSON.stringify(record, null, 2)}\n`, { encoding: 'utf-8', mode: 0o600 });
  await chmod(tmp, 0o600);
  await rename(tmp, filePath);
}
